server:
  port: 9000
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    lettuce:
      pool:
        max-active: 4
        max-wait: 30000
        min-idle: 0
        max-idle: 2
    timeout: 3000

middleware:
  redis:
    delay:
      consumers: 2